### ISSUE TITLE
Нужна карта сайта

### ISSUE THREAD

**Issue by f8upd8** [f8upd8/Product503#2]
Коротко - нужно изображение или что-то, что будет отражать структура сайта. То есть самое главное - с какой страницы на какую можно будет попасть.

**Comment by f8upd8** [comment]
Скинуть можно сюда, либо в телеграм.

**Comment by Anatohy** [comment]
![Карта сайта](https://user-images.githubusercontent.com/64703855/80914702-8d54f000-8d77-11ea-8914-cc2dd566dd6a.png)

**Comment by Anatohy** [comment]
Если нужно что-то добавить - говори

**Comment by f8upd8** [comment]
Нужно, чтобы если начинать с главной страницы, была возможность попасть на любую страницу на сайте. Иначе получается, что у нас страницы есть на которые попасть никак нельзя.

**Comment by Anatohy** [comment]
![Карта сайта1](https://user-images.githubusercontent.com/64703855/80918579-ec266380-8d8f-11ea-9604-99c410f1b47e.png)

**Comment by f8upd8** [comment]
Отличная работа, принято на вооружение.
