### ISSUE TITLE
Иконки

### ISSUE THREAD

**Issue by f8upd8** [f8upd8/Product503#4]
Нужны все иконки с дизайна сайта в формате .svg или в формате проекта иллюстратора. На крайняк - в .png не меньше чем 2048x2048 с прозрачностью. Пока делаю без них.

**Comment by Anatohy** [comment]
http://10.204.72.13/%D0%A8%D0%B0%D0%BF%D0%BA%D0%B0%202048.rar - шапка

**Comment by f8upd8** [comment]
Жду нижний разделитель, который между нижними ссылками и основной частью страницы

**Comment by f8upd8** [comment]
Шапка вроде как допилена

**Comment by f8upd8** [comment]
Сделай пожалуйста кнопки со страницы проектов фонда в векторе либо в пнг тоже, я их замучаюсь костылять

**Comment by f8upd8** [comment]
@Anatohy нужны изображения
