### ISSUE TITLE
Цвета шапки

### ISSUE THREAD

**Issue by Anatohy** [f8upd8/Product503#5]
![1](https://user-images.githubusercontent.com/64703855/81179589-110b1880-8fd4-11ea-90bc-e2b90a6be052.png)

**Comment by Anatohy** [comment]
Лично я вижу различия в цветах.
Вот цвета, которые я использовал:
c6e6f8        9cc2d9            859bac

**Comment by Anatohy** [comment]
![2](https://user-images.githubusercontent.com/64703855/81181720-1453d380-8fd7-11ea-965f-57c438755184.png)

**Comment by f8upd8** [comment]
![show](https://user-images.githubusercontent.com/25223886/81181964-6563c780-8fd7-11ea-9574-5743d2780d6e.png)

**Comment by Anatohy** [comment]
background: radial-gradient(circle at top, #c6e6f8  0%, #9cc2d9 45%, #859bac 100%);

**Comment by Anatohy** [comment]
Эти квадратики по бокам сделать немного меньше

**Comment by f8upd8** [comment]
> Эти квадратики по бокам сделать немного меньше

Не по теме

**Comment by f8upd8** [comment]
Цвета исправлены. Если проблема решена, закрой проблему или, если не найдешь как, отпиши

**Comment by f8upd8** [comment]
@Anatohy закрой тему если устраивают цвета
